// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) GOA_ERROR_ACCOUNT_EXISTS);
    PRINT_CONSTANT((gint) GOA_ERROR_DIALOG_DISMISSED);
    PRINT_CONSTANT((gint) GOA_ERROR_FAILED);
    PRINT_CONSTANT((gint) GOA_ERROR_NOT_AUTHORIZED);
    PRINT_CONSTANT((gint) GOA_ERROR_NOT_SUPPORTED);
    PRINT_CONSTANT(GOA_ERROR_NUM_ENTRIES);
    PRINT_CONSTANT((gint) GOA_ERROR_SSL);
    PRINT_CONSTANT(GOA_MAJOR_VERSION);
    PRINT_CONSTANT(GOA_MICRO_VERSION);
    PRINT_CONSTANT(GOA_MINOR_VERSION);
    return 0;
}
