// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*};
use std::{fmt};

glib::wrapper! {
    #[doc(alias = "GoaDocuments")]
    pub struct Documents(Interface<ffi::GoaDocuments, ffi::GoaDocumentsIface>);

    match fn {
        type_ => || ffi::goa_documents_get_type(),
    }
}

impl Documents {
        pub const NONE: Option<&'static Documents> = None;
    

    //#[doc(alias = "goa_documents_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:goa_documents_interface_info() }
    //}

    //#[doc(alias = "goa_documents_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:goa_documents_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::Documents>> Sealed for T {}
}

pub trait DocumentsExt: IsA<Documents> + sealed::Sealed + 'static {}

impl<O: IsA<Documents>> DocumentsExt for O {}

impl fmt::Display for Documents {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Documents")
    }
}
