// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*};
use std::{fmt};

glib::wrapper! {
    #[doc(alias = "GoaMaps")]
    pub struct Maps(Interface<ffi::GoaMaps, ffi::GoaMapsIface>);

    match fn {
        type_ => || ffi::goa_maps_get_type(),
    }
}

impl Maps {
        pub const NONE: Option<&'static Maps> = None;
    

    //#[doc(alias = "goa_maps_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:goa_maps_interface_info() }
    //}

    //#[doc(alias = "goa_maps_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:goa_maps_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::Maps>> Sealed for T {}
}

pub trait MapsExt: IsA<Maps> + sealed::Sealed + 'static {}

impl<O: IsA<Maps>> MapsExt for O {}

impl fmt::Display for Maps {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Maps")
    }
}
