// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_,fmt,mem::transmute};

glib::wrapper! {
    #[doc(alias = "GoaMediaServer")]
    pub struct MediaServer(Interface<ffi::GoaMediaServer, ffi::GoaMediaServerIface>);

    match fn {
        type_ => || ffi::goa_media_server_get_type(),
    }
}

impl MediaServer {
        pub const NONE: Option<&'static MediaServer> = None;
    

    //#[doc(alias = "goa_media_server_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:goa_media_server_interface_info() }
    //}

    //#[doc(alias = "goa_media_server_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:goa_media_server_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::MediaServer>> Sealed for T {}
}

pub trait MediaServerExt: IsA<MediaServer> + sealed::Sealed + 'static {
    #[doc(alias = "goa_media_server_dup_udn")]
    fn dup_udn(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_full(ffi::goa_media_server_dup_udn(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "goa_media_server_get_dlna_supported")]
    #[doc(alias = "get_dlna_supported")]
    fn is_dlna_supported(&self) -> bool {
        unsafe {
            from_glib(ffi::goa_media_server_get_dlna_supported(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "goa_media_server_get_udn")]
    #[doc(alias = "get_udn")]
    fn udn(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::goa_media_server_get_udn(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "goa_media_server_set_dlna_supported")]
    fn set_dlna_supported(&self, value: bool) {
        unsafe {
            ffi::goa_media_server_set_dlna_supported(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "goa_media_server_set_udn")]
    fn set_udn(&self, value: &str) {
        unsafe {
            ffi::goa_media_server_set_udn(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    #[cfg(feature = "v3_14")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v3_14")))]
    #[doc(alias = "dlna-supported")]
    fn connect_dlna_supported_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_dlna_supported_trampoline<P: IsA<MediaServer>, F: Fn(&P) + 'static>(this: *mut ffi::GoaMediaServer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(MediaServer::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::dlna-supported\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_dlna_supported_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[cfg(feature = "v3_14")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v3_14")))]
    #[doc(alias = "udn")]
    fn connect_udn_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_udn_trampoline<P: IsA<MediaServer>, F: Fn(&P) + 'static>(this: *mut ffi::GoaMediaServer, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(MediaServer::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::udn\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(notify_udn_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<MediaServer>> MediaServerExt for O {}

impl fmt::Display for MediaServer {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("MediaServer")
    }
}
