// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*};
use std::{fmt};

glib::wrapper! {
    #[doc(alias = "GoaMusic")]
    pub struct Music(Interface<ffi::GoaMusic, ffi::GoaMusicIface>);

    match fn {
        type_ => || ffi::goa_music_get_type(),
    }
}

impl Music {
        pub const NONE: Option<&'static Music> = None;
    

    //#[doc(alias = "goa_music_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:goa_music_interface_info() }
    //}

    //#[doc(alias = "goa_music_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:goa_music_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::Music>> Sealed for T {}
}

pub trait MusicExt: IsA<Music> + sealed::Sealed + 'static {}

impl<O: IsA<Music>> MusicExt for O {}

impl fmt::Display for Music {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Music")
    }
}
