// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*};
use std::{fmt};

glib::wrapper! {
    #[doc(alias = "GoaPhotos")]
    pub struct Photos(Interface<ffi::GoaPhotos, ffi::GoaPhotosIface>);

    match fn {
        type_ => || ffi::goa_photos_get_type(),
    }
}

impl Photos {
        pub const NONE: Option<&'static Photos> = None;
    

    //#[doc(alias = "goa_photos_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:goa_photos_interface_info() }
    //}

    //#[doc(alias = "goa_photos_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:goa_photos_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::Photos>> Sealed for T {}
}

pub trait PhotosExt: IsA<Photos> + sealed::Sealed + 'static {}

impl<O: IsA<Photos>> PhotosExt for O {}

impl fmt::Display for Photos {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Photos")
    }
}
