// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ..
// from ../gir-files
// DO NOT EDIT

use glib::{prelude::*};
use std::{fmt};

glib::wrapper! {
    #[doc(alias = "GoaReadLater")]
    pub struct ReadLater(Interface<ffi::GoaReadLater, ffi::GoaReadLaterIface>);

    match fn {
        type_ => || ffi::goa_read_later_get_type(),
    }
}

impl ReadLater {
        pub const NONE: Option<&'static ReadLater> = None;
    

    //#[doc(alias = "goa_read_later_interface_info")]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call ffi:goa_read_later_interface_info() }
    //}

    //#[doc(alias = "goa_read_later_override_properties")]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call ffi:goa_read_later_override_properties() }
    //}
}

mod sealed {
    pub trait Sealed {}
    impl<T: super::IsA<super::ReadLater>> Sealed for T {}
}

pub trait ReadLaterExt: IsA<ReadLater> + sealed::Sealed + 'static {}

impl<O: IsA<ReadLater>> ReadLaterExt for O {}

impl fmt::Display for ReadLater {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("ReadLater")
    }
}
